# Generated by Django 5.1.3 on 2024-11-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.product')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyBoughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequently_bought_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequently_bought_with_set', to='backend.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequently_bought_together_set', to='backend.product')),
            ],
            options={
                'unique_together': {('product', 'frequently_bought_product')},
            },
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_set', to='backend.product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_set', to='backend.product')),
            ],
            options={
                'unique_together': {('product', 'related_product')},
            },
        ),
    ]
